name: blackjack-store
services:
  postgres:
    image: postgres
    container_name: blackjack-store-postgres
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - blackjack-store_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  blackjack-store_postgres_data: